services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: flyssh
    networks:
      - config-manager_proxy


networks:
  config-manager_proxy:
    external: true
