services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: flyssh
    networks:
      - config-manager_proxy
    environment:
      - HOST_URL=flyssh.cantcode.fyi
    

networks:
  config-manager_proxy:
    external: true
