# Generated by Django 5.0.4 on 2024-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
