# Generated by Django 5.0.4 on 2024-04-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0002_user_master_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='master_key',
        ),
        migrations.AddField(
            model_name='user',
            name='decoded_secret',
            field=models.CharField(default='secret', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='encoded_secret',
            field=models.TextField(default='secret'),
        ),
    ]
