# Generated by Django 5.0.4 on 2024-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0003_remove_user_master_key_user_decoded_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='decoded_secret',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='encoded_secret',
            field=models.TextField(),
        ),
    ]
