# Generated by Django 5.0.4 on 2024-04-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0004_alter_user_avatar_alter_user_decoded_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='decoded_secret',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='encoded_secret',
            field=models.BinaryField(),
        ),
    ]
