# Generated by Django 5.0.4 on 2024-04-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0006_host_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='key',
        ),
    ]
