# Generated by Django 5.0.4 on 2024-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0007_remove_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
