# Generated by Django 5.0.4 on 2024-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0008_alter_host_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='passphrase',
            field=models.TextField(blank=True, null=True),
        ),
    ]
