# Generated by Django 5.0.4 on 2024-04-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0009_key_passphrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='name',
            new_name='label',
        ),
    ]
