# Generated by Django 5.0.4 on 2024-04-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyssh', '0011_alter_host_owner_alter_key_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host', to='flyssh.key'),
        ),
    ]
